const ERROR_CODES = {
    INGRESS_BUFFER_FULL: "INGRESS_BUFFER_FULL",
    INGRESS_BUFFER_EMPTY: "INGRESS_BUFFER_EMPTY",
    LOG_FILE_APPEND_FAILED: "LOG_FILE_APPEND_FAILED",
    INGRESS_BUFFER_BUILD_FAILED: "INGRESS_BUFFER_BUILD_FAILED",
    FILE_NOT_FOUND: "FILE_NOT_FOUND",
    DIRECTORY_NOT_FOUND: "DIRECTORY_NOT_FOUND",
    INVALID_FILE_PATH: "INVALID_FILE_PATH",
    INVALID_DIRECTORY_PATH: "INVALID_DIRECTORY_PATH",
}

export default ERROR_CODES;