const ERROR_CODES = {
    BUFFER_FULL: "BUFFER_FULL",
    BUFFER_EMPTY: "BUFFER_EMPTY",
    LOG_FILE_APPEND_FAILED: "LOG_FILE_APPEND_FAILED",
    BUFFER_BUILD_FAILED: "BUFFER_BUILD_FAILED",
    FILE_NOT_FOUND: "FILE_NOT_FOUND",
    DIRECTORY_NOT_FOUND: "DIRECTORY_NOT_FOUND",
    INVALID_FILE_PATH: "INVALID_FILE_PATH",
    INVALID_DIRECTORY_PATH: "INVALID_DIRECTORY_PATH",
    TOPIC_NOT_FOUND: "TOPIC_NOT_FOUND",
    PARTITION_NOT_FOUND: "PARTITION_NOT_FOUND",
    NO_PARTITION_AVAILABLE: "NO_PARTITION_AVAILABLE",
    INVALID_OFFSET: "INVALID_OFFSET",
    UNKNOWN_ERROR: "UNKNOWN_ERROR"
}

export default ERROR_CODES;